### PR TITLE
fix(HTTPClient): Use the correct constant for the iOS client OS name

### LINKED ISSUE #937: Minor typo on Constants.CLIENTS.IOS.NAME
### Steps to reproduce

Reading source code

### Failure Logs

In commit Constants.CLIENTS.IOS.NAME was used instead of Constants.CLIENTS.IOS.OS_NAME:
[https://github.com/LuanRT/YouTube.js/commit/219d88b2005431c6697f04e1fa2c5e8528a9ce57#diff-c8227dcc3018de210fd0227d87fe189d4ccf25904d88fccc23e4bd5d76b6f7ecR200](https://github.com/LuanRT/YouTube.js/commit/219d88b2005431c6697f04e1fa2c5e8528a9ce57#diff-c8227dcc3018de210fd0227d87fe189d4ccf25904d88fccc23e4bd5d76b6f7ecR200)

For now it is the same value but in future version it could be problematic

### Expected behavior

Constants.CLIENTS.IOS.OS_NAME

### Current behavior

Constants.CLIENTS.IOS.NAME

### PR DESCRIPTION
**Pull request by Brijeshthummar02**
closes #937

### CODE REVIEW

File: src/utils/HTTPClient.ts [hunk 1]
```diff
@@ -199,9 +199,9 @@ export default class HTTPClient {
         ctx.client.deviceMake = 'Apple';
         ctx.client.deviceModel = Constants.CLIENTS.IOS.DEVICE_MODEL;
         ctx.client.clientVersion = Constants.CLIENTS.IOS.VERSION;
-        ctx.client.clientName = Constants.CLIENTS.IOS.NAME;
+        ctx.client.clientName = Constants.CLIENTS.IOS.OS_NAME;
```
Comment (absidue) [inline src/utils/HTTPClient.ts:202]: Please revert this line, as the change to it is unnecessary.

Comment (Brijeshthummar02) [reply src/utils/HTTPClient.ts]: updated good to go?

**Comment by Brijeshthummar02** [comment]
@LuanRT good to merge?

**Review by LuanRT — APPROVED** [review]

**Comment by LuanRT** [comment]
Yes. Looks good to me now!
