### PR TITLE
fix(Session): Initialize client version based on provided client name

### LINKED ISSUE #970: [13.4.0] Innertube.session.client_version is constant (Constants.CLIENTS.WEB.VERSION)
### Steps to reproduce

see https://github.com/LuanRT/YouTube.js/blob/09718a717f49633f4382133050647fe4ff6ca007/src/core/Session.ts#L415

innertube.session.client_version is always initialized as Constants.CLIENTS.WEB.VERSION, unlike client_name.  this creates mismatched client name and versions.

Image
normally its not an issue, except when using [endpoint.call](https://github.com/LuanRT/YouTube.js/pull/151). I'm trying to [get ytmusic's chart](https://github.com/lovegaoshi/azusa-player-mobile/commit/60f5ff34f0e17a85a725db0a58be727724be9723#diff-26ad4b834941d9b19ebf9db8082bd202aaf72ea0ddea85f5a8a0cb3c729cc6f2R119) via [innertube.music.getExplore().top_buttons[1].endpoint](https://github.com/lovegaoshi/azusa-player-mobile/commit/60f5ff34f0e17a85a725db0a58be727724be9723#diff-26ad4b834941d9b19ebf9db8082bd202aaf72ea0ddea85f5a8a0cb3c729cc6f2R120), then [call endpoint.call(innertube.actions)](https://github.com/lovegaoshi/azusa-player-mobile/commit/60f5ff34f0e17a85a725db0a58be727724be9723#diff-26ad4b834941d9b19ebf9db8082bd202aaf72ea0ddea85f5a8a0cb3c729cc6f2R122); this always result in response 400

changing this line to something like `client_version: Object.values(Constants.CLIENTS).filter(v => v.NAME === client_name)[0]?.VERSION ?? Constants.CLIENTS.WEB.VERSION,` ([patch-package](https://github.com/lovegaoshi/azusa-player-mobile/commit/60f5ff34f0e17a85a725db0a58be727724be9723#diff-4dec28af4a87ad88f320633a6b33659227780a4de5b6883366aac5ce10c4f317R73)) works

### Failure Logs

```shell
code:404
message:Requested entity was not found.
status:NOT_FOUND
```

### Expected behavior

200

### Current behavior

404

### Version

Default

### Anything else?

_No response_

### Checklist

- [ ] I am running the latest version.
- [x] I checked the documentation and found no answer.
- [x] I have searched the existing issues and made sure this is not a duplicate.
- [x] I have provided sufficient information.

### PR DESCRIPTION
**Pull request by lovegaoshi**
fixes #970 

testing:
---

```
const yt = await Innertube.create({client_type: ClientType.MUSIC});
console.log(yt.session) 
```
before:
shows client.version = 2.xxx which is web's

after:
should show 1.xxx

### CODE REVIEW

File: src/core/Session.ts [hunk 1]
```diff
@@ -554,7 +565,9 @@ export default class Session extends EventEmitter {
       visitor_data: options.visitor_data || device_info[13],
       user_agent: options.user_agent,
       client_name: options.client_name,
-      client_version: device_info[16],
+      client_version: Object.values(Constants.CLIENTS).filter(
+        (v) => v.NAME === options.client_name
+      )[0]?.VERSION ?? device_info[16],
```
Comment (absidue) [inline src/core/Session.ts:570]: The way this is written means it will always use the version from the constants, instead of the one fetched remotely, but for WEB it should always use the latest version.
