### PR TITLE
fix: `LiveChatAuthorBadge` where `MetadataBadge` was expected

### LINKED ISSUE #178: 2.0.2 Error: Type mismatch, got LiveChatAuthorBadge but expected MetadataBadge
### Steps to reproduce

```javascript
import { Innertube, UniversalCache } from "youtubei.js";

import { ChatAction } from "youtubei.js/dist/src/parser/youtube/LiveChat";

import AddChatItemAction from "youtubei.js/dist/src/parser/classes/livechat/AddChatItemAction";

import LiveChatTextMessage from "youtubei.js/dist/src/parser/classes/livechat/items/LiveChatTextMessage";
import LiveChatPaidMessage from "youtubei.js/dist/src/parser/classes/livechat/items/LiveChatPaidMessage";

(async () => {
  const yt = await Innertube.create({ cache: new UniversalCache() });

  const info = await yt.getInfo("any live stream video id");
  const livechat = await info.getLiveChat();

  livechat.on("chat-update", (action: ChatAction) => {
    if (action.is(AddChatItemAction)) {
      const item = action.as(AddChatItemAction).item;

      if (!item) return console.info("Action did not have an item.", action);

      const hours = new Date(
        item.hasKey("timestamp") ? item.timestamp : Date.now()
      ).toLocaleTimeString("en-US", {
        hour: "2-digit",
        minute: "2-digit",
      });

      switch (item.type) {
        case "LiveChatTextMessage":
          console.info(
            `${hours} - ${item
              .as(LiveChatTextMessage)
              .author?.name.toString()}:\n` +
              `${item.as(LiveChatTextMessage).message.toString()}\n`
          );
          break;
        case "LiveChatPaidMessage":
          console.info(
            `${hours} - ${item
              .as(LiveChatPaidMessage)
              .author.name.toString()}:\n` +
              `${item.as(LiveChatPaidMessage).purchase_amount}\n`
          );
          break;
        default:
          console.debug(action);
          break;
      }
    }
  });

  livechat.start();
})();
```

### Failure Logs

```shell
InnertubeError: Something went wrong at LiveChatAuthorBadge!
This is a bug, please report it at https://github.com/LuanRT/YouTube.js/issues
    at Function.formatError (C:\PROJECT_DIR\node_modules\youtubei.js\src\parser\index.ts:451:7)
    at Function.parseItem (C:\PROJECT_DIR\node_modules\youtubei.js\src\parser\index.ts:348:14)
    at Function.parseArray (C:\PROJECT_DIR\node_modules\youtubei.js\src\parser\index.ts:361:29)
    at new LiveChatPaidMessage (C:\PROJECT_DIR\node_modules\youtubei.js\src\parser\classes\livechat\items\LiveChatPaidMessage.ts:47:27)
    at Function.parseItem (C:\PROJECT_DIR\node_modules\youtubei.js\src\parser\index.ts:343:24)
    at Function.parse (C:\PROJECT_DIR\node_modules\youtubei.js\src\parser\index.ts:400:39)
    at new LiveChatTickerPaidMessageItem (C:\PROJECT_DIR\node_modules\youtubei.js\src\parser\classes\livechat\items\LiveChatTickerPaidMessageItem.ts:49:29)
    at Function.parseItem (C:\PROJECT_DIR\node_modules\youtubei.js\src\parser\index.ts:343:24)
    at new AddLiveChatTickerItemAction (C:\PROJECT_DIR\node_modules\youtubei.js\src\parser\classes\livechat\AddLiveChatTickerItemAction.ts:12:24)
    at Function.parseItem (C:\PROJECT_DIR\node_modules\youtubei.js\src\parser\index.ts:343:24) {
  info: {
    stack: 'Error: Type mismatch, got LiveChatAuthorBadge but expected MetadataBadge\n' +
      '    at Function.parseItem (C:\\PROJECT_DIR\\node_modules\\youtubei.js\\src\\parser\\index.ts:340:19)\n' +
      '    at Function.parseArray (C:\\PROJECT_DIR\\node_modules\\youtubei.js\\src\\parser\\index.ts:361:29)\n' +
      '    at new LiveChatPaidMessage (C:\\PROJECT_DIR\\node_modules\\youtubei.js\\src\\parser\\classes\\livechat\\items\\LiveChatPaidMessage.ts:47:27)\n' +
      '    at Function.parseItem (C:\\PROJECT_DIR\\node_modules\\youtubei.js\\src\\parser\\index.ts:343:24)\n' +
      '    at Function.parse (C:\\PROJECT_DIR\\node_modules\\youtubei.js\\src\\parser\\index.ts:400:39)\n' +
      '    at new LiveChatTickerPaidMessageItem (C:\\PROJECT_DIR\\node_modules\\youtubei.js\\src\\parser\\classes\\livechat\\items\\LiveChatTickerPaidMessageItem.ts:49:29)\n' +
      '    at Function.parseItem (C:\\PROJECT_DIR\\node_modules\\youtubei.js\\src\\parser\\index.ts:343:24)\n' +
      '    at new AddLiveChatTickerItemAction (C:\\PROJECT_DIR\\node_modules\\youtubei.js\\src\\parser\\classes\\livechat\\AddLiveChatTickerItemAction.ts:12:24)\n' +
      '    at Function.parseItem (C:\\PROJECT_DIR\\node_modules\\youtubei.js\\src\\parser\\index.ts:343:24)\n' +
      '    at Function.parse (C:\\PROJECT_DIR\\node_modules\\youtubei.js\\src\\parser\\index.ts:387:29)'
  },
  date: 2022-09-09T19:37:05.766Z,
  version: '2.0.2'
}

InnertubeError: Something went wrong at LiveChatAuthorBadge!
This is a bug, please report it at https://github.com/LuanRT/YouTube.js/issues
    at Function.formatError (C:\PROJECT_DIR\node_modules\youtubei.js\src\parser\index.ts:451:7)
    at Function.parseItem (C:\PROJECT_DIR\node_modules\youtubei.js\src\parser\index.ts:348:14)
    at Function.parseArray (C:\PROJECT_DIR\node_modules\youtubei.js\src\parser\index.ts:361:29)
    at new LiveChatTextMessage (C:\PROJECT_DIR\node_modules\youtubei.js\src\parser\classes\livechat\items\LiveChatTextMessage.ts:41:27)
    at Function.parseItem (C:\PROJECT_DIR\node_modules\youtubei.js\src\parser\index.ts:343:24)
    at new AddChatItemAction (C:\PROJECT_DIR\node_modules\youtubei.js\src\parser\classes\livechat\AddChatItemAction.ts:12:24)
    at Function.parseItem (C:\PROJECT_DIR\node_modules\youtubei.js\src\parser\index.ts:343:24)
    at Function.parse (C:\PROJECT_DIR\node_modules\youtubei.js\src\parser\index.ts:387:29)
    at new LiveChatContinuation (C:\PROJECT_DIR\node_modules\youtubei.js\src\parser\index.ts:143:27)
    at Function.parseLC (C:\PROJECT_DIR\node_modules\youtubei.js\src\parser\index.ts:291:14) {
  info: {
    stack: 'Error: Type mismatch, got LiveChatAuthorBadge but expected MetadataBadge\n' +
      '    at Function.parseItem (C:\\PROJECT_DIR\\node_modules\\youtubei.js\\src\\parser\\index.ts:340:19)\n' +
      '    at Function.parseArray (C:\\PROJECT_DIR\\node_modules\\youtubei.js\\src\\parser\\index.ts:361:29)\n' +
      '    at new LiveChatTextMessage (C:\\PROJECT_DIR\\node_modules\\youtubei.js\\src\\parser\\classes\\livechat\\items\\LiveChatTextMessage.ts:41:27)\n' +
      '    at Function.parseItem (C:\\PROJECT_DIR\\node_modules\\youtubei.js\\src\\parser\\index.ts:343:24)\n' +
      '    at new AddChatItemAction (C:\\PROJECT_DIR\\node_modules\\youtubei.js\\src\\parser\\classes\\livechat\\AddChatItemAction.ts:12:24)\n' +
      '    at Function.parseItem (C:\\PROJECT_DIR\\node_modules\\youtubei.js\\src\\parser\\index.ts:343:24)\n' +
      '    at Function.parse (C:\\PROJECT_DIR\\node_modules\\youtubei.js\\src\\parser\\index.ts:387:29)\n' +
      '    at new LiveChatContinuation (C:\\PROJECT_DIR\\node_modules\\youtubei.js\\src\\parser\\index.ts:143:27)\n' +
      '    at Function.parseLC (C:\\PROJECT_DIR\\node_modules\\youtubei.js\\src\\parser\\index.ts:291:14)\n' +
      '    at Function.parseResponse (C:\\PROJECT_DIR\\node_modules\\youtubei.js\\src\\parser\\index.ts:246:65)'
  },
  date: 2022-09-09T19:37:05.780Z,
  version: '2.0.2'
}
```

### Expected behavior

No error thrown when expecting and using the right class `LiveChatAuthorBadge`.

### Current behavior

Expects `MetadataBadge` while `LiveChatAuthorBadge` should be expected, causing an error to be thrown.

### Version

Default

### Anything else?

_No response_

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

### PR DESCRIPTION
**Pull request by Rydann**
## Description

Fixes #178

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

File: src/parser/classes/livechat/items/LiveChatPaidMessage.ts [hunk 1]
```diff
@@ -38,13 +38,13 @@ class LiveChatPaidMessage extends YTNode {
       id: data.authorExternalChannelId,
       name: new Text(data.authorName),
       thumbnails: Thumbnail.fromResponse(data.authorPhoto),
-      badges: Parser.parseArray<MetadataBadge>(data.authorBadges, MetadataBadge),
```
Comment (Wykerd) [inline src/parser/classes/livechat/items/LiveChatPaidMessage.ts:41]: There's probably a good reason why this was typed `MetadataBadge`. Maybe opt for using `Parser.parseArray<LiveChatAuthorBadge | MetadataBadge>(data.authorBadges, [MetadataBadge, LiveChatAuthorBadge])` instead?

Comment (Rydann) [reply src/parser/classes/livechat/items/LiveChatPaidMessage.ts:41]: I haven't run into any case where this was necessary over the past 12 hours, but having a "failsafe" is never a bad idea, you got a point.
Let me add that to the other classes as well just in case.

**Review by LuanRT — APPROVED** [review]
